
LOG_BACK_TYPE = {}
LOG_BACK_TYPE.LOG_SUCCESS = 1		--登录成功
LOG_BACK_TYPE.LOG_CREATE_PLAYER = 2	--创建玩家
LOG_BACK_TYPE.LOG_PLAYER_EXIEST = 3	--玩家已存在
LOG_BACK_TYPE.LOG_PLAYER_OTHER = 4	--玩家在别处登录
LOG_BACK_TYPE.LOG_GAME_SHUT = 5		--游戏在维护
LOG_BACK_TYPE.LOG_GAME_FULL = 6		--游戏人数已满
LOG_BACK_TYPE.LOG_MAX_ONLINE = 7	--在线人数已达上限
