--PlayerMacro.lua
--Player的全局宏
require "resource.script.server.Config.Player.FUNCTIONCFG"

local PlayerMacro = {}
PlayerMacro.NOTERM 			= 0		--无条件
PlayerMacro.COMPLETETASK 	= 1		--主线任务
PlayerMacro.PLAYERLEVEL	 	= 2		--人物等级
PlayerMacro.BUILD 			= 3		--建筑
PlayerMacro.SPACE			= 4		--二级副本ID
PlayerMacro.GETITEM			= 5		--获得物品
PlayerMacro.BIGMAP			= 6		--大副本ID
PlayerMacro.OPENSYS			= 7		--开放模块


PLAYER_PROP_TYPE = {}
PLAYER_PROP_TYPE.PLAYERLEVEL = 1
PLAYER_PROP_TYPE.PLAYEREXP = 2
PLAYER_PROP_TYPE.PLAYERDIAMOND = 3
PLAYER_PROP_TYPE.PLAYERCOPPER = 4
--PLAYER_PROP_TYPE.PLAYERWOOD = 5
--PLAYER_PROP_TYPE.PLAYERFUR = 6
--PLAYER_PROP_TYPE.PLAYERMEAT = 7
--PLAYER_PROP_TYPE.PLAYERBONFIRESTATE = 9
PLAYER_PROP_TYPE.PLAYERBEARLOAD = 10
PLAYER_PROP_TYPE.PLAYERRENKOUTOTAL = 11
PLAYER_PROP_TYPE.PLAYERTALENTPOINT = 12--成就点
--PLAYER_PROP_TYPE.ROLELOGINDAYS = 14
PLAYER_PROP_TYPE.PLAYERSYSTEMSTATE = 15	--开放的系统功能

LOG_BACK_TYPE = {}
LOG_BACK_TYPE.LOG_SUCCESS = 1		--登录成功
LOG_BACK_TYPE.LOG_CREATE_PLAYER = 2	--创建玩家
LOG_BACK_TYPE.LOG_PLAYER_EXIEST = 3	--玩家已存在
LOG_BACK_TYPE.LOG_PLAYER_OTHER = 4	--玩家在别处登录
LOG_BACK_TYPE.LOG_GAME_SHUT = 5		--游戏在维护
LOG_BACK_TYPE.LOG_GAME_FULL = 6		--游戏人数已满
LOG_BACK_TYPE.LOG_MAX_ONLINE = 7	--在线人数已达上限

FUNCTION_ID_TYPE = {}
FUNCTION_ID_TYPE.GOLD = 11          --炼金功能
FUNCTION_ID_TYPE.BUILD = 12         --建造功能
FUNCTION_ID_TYPE.WAREHOUSE = 13     --仓库功能
FUNCTION_ID_TYPE.PEOPLE = 14        --人口分配功能
FUNCTION_ID_TYPE.ADVENTURES = 15    --冒险者功能
FUNCTION_ID_TYPE.EXPLORE = 16       --探险功能
FUNCTION_ID_TYPE.SHOP = 17          --商店功能
FUNCTION_ID_TYPE.MAKE = 18          --打造功能
FUNCTION_ID_TYPE.EVENT = 19         --事件功能
FUNCTION_ID_TYPE.TALENT = 20        --天赋功能
FUNCTION_ID_TYPE.ACHIEVEMENT = 21   --成就功能


PLAYERSTATUS = {}
PLAYERSTATUS.INNERCITY = 0			--城内
PLAYERSTATUS.EXPLORE = 1			--探险

--读取功能配置
function PlayerMacro:readFunctionCfg(functionID)
	local ID  = "FUNCTIONID_"..functionID
	return FUNCTIONCFG[ID]
end

return {PlayerMacro = PlayerMacro}